title: Mouhsen Ibrahim Site
description: >
  In this website I will post articles about Linux, DevOps and Database Administration and many other topics
  such as ELK, Development environments with vagrant and docker if you have any questions please contact me
  at mohsen47@hotmail.co.uk.
base_url: ''
show_downloads: false

theme: jekyll-theme-hacker
