# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mouhsen Ibrahim Site
email: mohsen47@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  In this website I will post articles about Linux, DevOps and Database Administration and many other topics
  such as ELK, Development environments with vagrant and docker if you have any questions please contact me
  at mohsen47@hotmail.co.uk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mohsenSy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mouhsen_ibrahim
github_username:  mohsenSy
facebook_username: mohsen.ibrahim.5055
linkedin_username: mouhsen-ibrahim-670b13112/
google_analytics: UA-102239605-1

name: Mouhsen

disqus:
  shortname: mohsensy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
